name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calver Release
        uses: StephaneBour/actions-calver@v1.4
        id: calver
        with:
          date_format: "%Y.%m.%d"
          release_branch: main
          release: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set Install Chart Version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.version = strenv(VERSION)' 'helm/install/Chart.yaml'
        env:
          VERSION: ${{ steps.calver.outputs.release }}

      - name: Set Cluster Chart Version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.version = strenv(VERSION)' 'helm/postgres/Chart.yaml'
        env:
          VERSION: ${{ steps.calver.outputs.release }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
