name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Build ID
        id: calver
        run: |
          # run=$(( GITHUB_RUN_NUMBER % 10 ))
          run=${GITHUB_RUN_NUMBER}
          ts=$(date +%Y.%m.%d)
          echo "::set-output name=BUILD_ID::${ts}-${run}"

      - name: Publish Helm Charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: helm/install
          chart_version: ${{ steps.calver.outputs.BUILD_ID }}

      - name: Publish Helm Charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: helm/postgres
          chart_version: ${{ steps.calver.outputs.BUILD_ID }}
